### ISSUE TITLE
Update form_builder_validators to intl ^0.19.0 package

### ISSUE THREAD

**Issue by nikel-abibiano** [flutter-form-builder-ecosystem/form_builder_validators#92] opened 2024-05-14 07:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.0

### Platforms

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [X] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Versi¢n 10.0.22631.3527], locale es-ES)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
[√] Android Studio (version 2023.2)
[√] VS Code, 64-bit edition (version 1.89.1)
[√] Connected device (1 available)
[√] Network resources
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
flutter pub update
```

</details>

### Current Behavior

flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required
form_builder_validators ^9.1.0, version solving failed because dependes on intl ^0.18.0

### Expected Behavior

flutter pub update updates to latest packaged using intl 0.19.0

### Steps To Reproduce

flutter pub update

**Comment by JakobLichterfeld** [comment] 2024-05-14 07:17
duplicate of  #90 which has more info and a workaround

**Closed** 2024-05-16 18:25 UTC
Labels: bug

**Comment by deandreamatias** [comment] 2024-05-22 15:45
Version 10.0.0 with fix, deployed https://pub.dev/packages/form_builder_validators
